### ISSUE TITLE
Use uvicorn to run the deviceregistry

### ISSUE THREAD

**Issue by laurigates** [City-of-Helsinki/mittaridatapumppu#4]
It would probably be better to run the deviceregistry app in uvicorn instead of using the development server:

https://github.com/City-of-Helsinki/mittaridatapumppu/blob/6f4da261752249fbea76f2e44b6ebccc25aa2794/service-deviceregistry/Dockerfile#LL32C1-L32C44

Should be changed to something like:

https://github.com/City-of-Helsinki/mittaridatapumppu/blob/6f4da261752249fbea76f2e44b6ebccc25aa2794/service-endpoint/Dockerfile#L18

**Comment by aapris** [comment]
In Djangos case it would be gunicorn, something like this:
`gunicorn deviceregistry.wsgi:application --bind 0.0.0.0:8000 --access-logfile access.log --error-logfile error.log --capture-output --workers 4`
We also want to use development server while developing, so `python manage.py runserver` should be available somewhere in docker-compose.yml?

**Comment by laurigates** [comment]
The logs would probably be best to go to stdout for now (so probably just remove the options). The settings can be overriden using environment variables if needed.

The command can be overriden in docker-compose using `command` setting if needed.

Apparently django can be run in uvicorn as well, though I don't know all the implications of this. It would mean only one worker per pod, which might make metrics easier to read and Kubernetes would handle the lifecycle of each process. On the other hand, if gunicorn handles workers they **might** start a bit faster. Probably won't make a difference in this case, but might be worth exploring at some point.

https://docs.djangoproject.com/en/4.2/howto/deployment/asgi/uvicorn/
